
package soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "HotelReservationServiceImplService", targetNamespace = "http://soap/", wsdlLocation = "http://localhost:8082/HotelReservationService?wsdl")
public class HotelReservationServiceImplService
    extends Service
{

    private static final URL HOTELRESERVATIONSERVICEIMPLSERVICE_WSDL_LOCATION;
    private static final WebServiceException HOTELRESERVATIONSERVICEIMPLSERVICE_EXCEPTION;
    private static final QName HOTELRESERVATIONSERVICEIMPLSERVICE_QNAME = new QName("http://soap/", "HotelReservationServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/HotelReservationService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HOTELRESERVATIONSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        HOTELRESERVATIONSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public HotelReservationServiceImplService() {
        super(__getWsdlLocation(), HOTELRESERVATIONSERVICEIMPLSERVICE_QNAME);
    }

    public HotelReservationServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HOTELRESERVATIONSERVICEIMPLSERVICE_QNAME, features);
    }

    public HotelReservationServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, HOTELRESERVATIONSERVICEIMPLSERVICE_QNAME);
    }

    public HotelReservationServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HOTELRESERVATIONSERVICEIMPLSERVICE_QNAME, features);
    }

    public HotelReservationServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HotelReservationServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HotelReservationService
     */
    @WebEndpoint(name = "HotelReservationServiceImplPort")
    public HotelReservationService getHotelReservationServiceImplPort() {
        return super.getPort(new QName("http://soap/", "HotelReservationServiceImplPort"), HotelReservationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HotelReservationService
     */
    @WebEndpoint(name = "HotelReservationServiceImplPort")
    public HotelReservationService getHotelReservationServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap/", "HotelReservationServiceImplPort"), HotelReservationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HOTELRESERVATIONSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw HOTELRESERVATIONSERVICEIMPLSERVICE_EXCEPTION;
        }
        return HOTELRESERVATIONSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
